### ISSUE TITLE
Does not load on Django 4 / netbox 3.2

### ISSUE THREAD

**Issue by squintfox** [jeremyschulman/django3-auth-saml2#14]
netbox 3.2 (currently in beta, releasing in April) is moving to Django 4.  Django 4 has deprecated the method is_safe_url() in utils.http (which is used in views.py).  It is replaced with url_has_allowed_host_and_scheme() (same parameters).  When you load the netbox beta, you get:

ImportError: cannot import name 'is_safe_url' from 'django.utils.http' (/opt/netbox/venv/lib/python3.9/site-packages/django/utils/http.py)

I know this specifies django3, but netbox-plugin-auth-saml2 requires this and will no longer work.  Are there any thoughts on making this compatible with Django 4 or making a version for netbox that can be?

**Comment by squintfox** [comment]
I added a PR with the suggested change. [https://github.com/jeremyschulman/django3-auth-saml2/pull/15](url)

This should be fine on any version of Django 3 and works in Django 4.

**Comment by jeremyschulman** [comment]
PR merged and released v0.4.0 to pypi.

**Comment by jeremyschulman** [comment]
thank you again @squintfox

**Comment by squintfox** [comment]
You're very welcome, Thank you too, @jeremyschulman
